### ISSUE TITLE
First Library Based on Known Literature Inhibitor

### ISSUE THREAD

**Issue by mattodd** [StructuralGenomicsConsortium/CNP6-ABHD2#1]
The only known inhibitor of ABHD2 (paper [here](https://pubs.acs.org/doi/10.1021/acschembio.9b00640)) that possessed good selectivity in an activity-based protein profiling screen was this one:

![Picture1](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/assets/112560282/87d65768-86d5-4fa1-88fe-0efc50793f5e)

Evert Homan from Thomas Helleday's group at the Karolinska Institute has completed a targeted library of some analogs, containing these molecules:

<img width="691" alt="image" src="https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/assets/112560282/715e4c8f-0019-4945-9fc2-dc6988779422">

Datawarrior file:  [ABHD2_Paulina.dwar](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/blob/main/File%20Diary/Urea%20Compounds/Older/ABHD2_Pauline.dwar)

The synthesis was carried out by Pauline Ribera, a Masters student from SIGMA Clermont Graduate School of Engineering in Aubière, France, supervised by @MartinHaraldsson and Tobias Koolmeister. See her report: [Pauline Ribera report.pdf](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/blob/main/File%20Diary/Urea%20Compounds/Older/Pauline.Ribera.report.pdf)

 Kirsty Bentley (presently back at Edinburgh University) resynthesized the original ABHD2 hit compound while doing an internship at the Helleday lab. See her synthesis: [ABHD2i_synthesis_220216.Kirsty.Bentley.pptx](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/blob/main/File%20Diary/Urea%20Compounds/Older/ABHD2i_synthesis_Kirsty.Bentley.pptx)

These are scheduled for evaluation vs ABHD2 by Oliver Arnolds, Karolinska.

While we await data, @EveCarter was considering which close analogs might already be commercially available, and came up with the following list. These can be acquired now, or wait until we have the preliminary data back.

Datawarrior: [ABHD2 potential inhibitors_Eve_221003.dwar](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/blob/main/File%20Diary/Urea%20Compounds/2022/ABHD2%20potential%20inhibitors_Eve_221003.dwar)

**Comment by ghost** [comment]
Hi Matt, I think we should just go ahead and order the compounds Eve has proposed, under the assumption that we will get an enzymatic assay up and running quite soon. Martin Haraldsson suggested that CBCS in Stockholm should take care of compound handling (they have an excellent infrastructure for this), so in that case we could place the order here and also take the tab. BW/Evert

**Comment by mattodd** [comment]
The compounds are all a good fit with the existing set, so I think they're all reasonable.

If they can be ordered to go to Stockholm, then great. It'd be good to have Oliver on here - I'll ping him again. These are nice compounds, and it'd be very good if we could coordinate their addition to SGC more generally e.g. by submitting some 10mM stocks to Frankfurt? Lots of viral targets we might want to screen against...

@Evert-Homan did you have a robust synthetic route you could share?

@EveCarter I'm seeing quite diverse motifs here. If you could use Datawarrior to assess logP for these two sets, to see how we're looking, that'd be good. And are there any motifs we could introduce ourselves for things that are not simply commercially available? e.g. Thiourea/thioamide? Any bioisosteres of amides/ureas?

**Comment by mattodd** [comment]
FYI all Oliver is now on here @OliverArnolds, so we can correspond generally about the protein/assay. Hi Oliver.
And yes, we should always cross-reference to other relevant resources like the openlabnotebooks site and Oliver's very nice post [here](https://openlabnotebooks.org/a-promising-target-for-non-hormonal-contraception-the-%ce%b1-%ce%b2-hydrolase-domain-2/).

**Comment by EveCarter** [comment]
Here are the cLogP calculated by Data Warrior for Pauline Ribera's compounds:
<img width="699" alt="220921 with cLogP" src="https://user-images.githubusercontent.com/112560282/193569780-e812191d-3205-4a4f-810a-f81404fa75e7.PNG">


And for my set of compounds:
<img width="670" alt="221003 with cLogP" src="https://user-images.githubusercontent.com/112560282/193569909-56aa5f77-dc12-4c55-981e-3573482852e7.PNG">

I have added a few more so here is the new data warrior file: [ABHD2 potential inhibitors_Eve_221003.zip](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/files/9697166/ABHD2.potential.inhibitors_Eve_221003.zip)

**Comment by mattodd** [comment]
@EveCarter half of each set having clogP < 3 is not bad at this stage, I'd say.

**Comment by mattodd** [comment]
@Evert-Homan kindly provided this slide describing the resynthesis of the original hit compound by Kirsty Bentley, who was an intern in the Helleday lab.

[ABHD2i_synthesis_220216 Kirsty Bentley.pptx](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/files/9698700/ABHD2i_synthesis_220216.Kirsty.Bentley.pptx)

@EveCarter how might we be able to "un-triphosgene" this prep while still keeping it simple for the ureas?

**Comment by MartinHaraldsson** [comment]
Regarding the use of phosgene or other alternatives to make the ureas, Pauline did not spend much time to evaluate this and at the scale the work was done it did not present any safety concerns. If, however, a scaleup is to be done and getting better yields I think the protocol needs some attention. It can be difficult to find really benign reagents that work, but this link gives a bit of insight.

https://www.sigmaaldrich.com/SE/en/technical-documents/technical-article/chemistry-and-synthesis/reaction-design-and-optimization/phosgene-and-substitutes

**Comment by EveCarter** [comment]
A quick SciFinder search didn't come up with any great alternatives. People tend to use phosgene or triphosgene for this reaction, or form the carboxylic acid with CO2 then use PCl5 or SOCl2.

**Comment by ghost** [comment]
@EveCarter As I want to put in an order soon I went through your update DataWarrior file with 28 compounds. Most of them are indeed available from Enamine with a few exceptions. Hoever I could not at all find compound 12 with CAS # 1645475-91-7, a search in PubChem does not give any hits...are you sure Enamine has it? Let me know their catalogue number in that case!

**Comment by EveCarter** [comment]
I just realised that I have drawn that structure wrong, sorry! That CAS number and the structure I meant has a meta methoxy group on the aromatic ring not para. I just found it on enamine, the product ID is Z1822615731.

![image](https://user-images.githubusercontent.com/112560282/194107437-f4214392-d1a3-4f30-aaf5-5e7ef3999634.png)

**Comment by MartinHaraldsson** [comment]
Ok
When we order we will use the CAS# and then check we have no doublets and also touch base with you
Martin

Martin
________________________________
Från: EveCarter ***@***.***>
Skickat: Wednesday, October 5, 2022 6:04:27 PM
Till: StructuralGenomicsConsortium/CNP6-ABHD2 ***@***.***>
Kopia: Martin Haraldsson ***@***.***>; Mention ***@***.***>
Ämne: Re: [StructuralGenomicsConsortium/CNP6-ABHD2] First Library Based on Known Literature Inhibitor (Issue #1)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I just realised that I have drawn that structure wrong, sorry! That CAS number and the structure I meant has a meta methoxy group on the aromatic ring not para. I just found it on enamine, the product ID is Z1822615731.

[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F112560282%2F194107437-f4214392-d1a3-4f30-aaf5-5e7ef3999634.png&data=05%7C01%7Cmartin.haraldsson%40ki.se%7C865b0a6c100141c915f608daa6eb480d%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638005826697953633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OGmnTsWQ4Hr94LEdEK6RlW3SH9AYx0qq%2BipRWVFT5zc%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FStructuralGenomicsConsortium%2FCNP6-ABHD2%2Fissues%2F1%23issuecomment-1268632611&data=05%7C01%7Cmartin.haraldsson%40ki.se%7C865b0a6c100141c915f608daa6eb480d%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638005826697953633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GznhHuONWZeo2aIz07Ws0KR6stKev4AWz83pilm5Kxc%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA3M3VXFU73FSA5ONV4E3SFLWBWRIXANCNFSM6AAAAAAQYYMTMA&data=05%7C01%7Cmartin.haraldsson%40ki.se%7C865b0a6c100141c915f608daa6eb480d%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638005826697953633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cBcSnWPy2JTRUb%2BAP60M1EIdSv32FwnUj%2BaOHJOGEcU%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by ghost** [comment]
> I just realised that I have drawn that structure wrong, sorry! That CAS number and the structure I meant has a meta methoxy group on the aromatic ring not para. I just found it on enamine, the product ID is Z1822615731.
> 
> ![image](https://user-images.githubusercontent.com/112560282/194107437-f4214392-d1a3-4f30-aaf5-5e7ef3999634.png)

This makes it identical to structure #27...so in essence there are 26 compounds on the list, right? Martin will check if any of these are already in the CBCS collection, then we will go ahead an place the order.

/E

**Comment by EveCarter** [comment]
Yes you are correct - now 12 has the right structure it is the same as 27, so there are only 26 compounds. Sorry, my fault, I should have noticed they had the same CAS and one was drawn wrong!

**Comment by EveCarter** [comment]
Was everything okay with ordering the rest of these chemicals? @Evert-Homan

**Comment by ghost** [comment]
@EveCarter  I have ordered 22 cpds from Enamine, will try to order the remaining 4 asap

**Comment by ghost** [comment]
@EveCarter We decided to go for 2 mg in the first round. Based on the first compounds synthesized some may be oils rather than solids which makes it very hard to weigh out small amounts. We will get exact amounts weighed out so can dissolve everything to 10 mM DMSO stock. This should give 500-700 µL of stock, which is plenty to start with. If we find really interesting ones we can order or make more.

**Comment by ghost** [comment]
@OliverArnolds @MartinHaraldsson @mattodd @EveCarter Since I plan to order 3 of the 4 remaining through MolPort, how do you guys feel about also ordering a bunch of reference ligands for other ABHD enzymes. These may also be useful for the EUbOPEN chemogenomics library. What do you think? Let me know if you have any special desires. I will select primarily based on data in Probes & Drugs: https://www.probes-drugs.org/compounds/standardized#customset=714@AND

**Comment by MartinHaraldsson** [comment]
I think It make sense to have the reference ligands. I vote for that.

Martin
________________________________
Från: Evert-Homan ***@***.***>
Skickat: Thursday, October 13, 2022 4:33:01 PM
Till: StructuralGenomicsConsortium/CNP6-ABHD2 ***@***.***>
Kopia: Martin Haraldsson ***@***.***>; Mention ***@***.***>
Ämne: Re: [StructuralGenomicsConsortium/CNP6-ABHD2] First Library Based on Known Literature Inhibitor (Issue #1)


@OliverArnolds<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOliverArnolds&data=05%7C01%7Cmartin.haraldsson%40ki.se%7C9159f85324304f72c98408daad27d5fd%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638012683848289575%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=U35ONsZUEIt1aXLRahJajTGyu5Rwywk5CIugV0DO2GA%3D&reserved=0> @MartinHaraldsson<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMartinHaraldsson&data=05%7C01%7Cmartin.haraldsson%40ki.se%7C9159f85324304f72c98408daad27d5fd%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638012683848289575%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qQ2RSKImjxXTS45ux%2FF3AcMAqGwxIYtAi6cRFRdrCgg%3D&reserved=0> @mattodd<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmattodd&data=05%7C01%7Cmartin.haraldsson%40ki.se%7C9159f85324304f72c98408daad27d5fd%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638012683848289575%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0Dgkk2Wge%2FUYGqsFyoYx9FdEAtoTVvBV5CSGrYUR7n8%3D&reserved=0> @EveCarter<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEveCarter&data=05%7C01%7Cmartin.haraldsson%40ki.se%7C9159f85324304f72c98408daad27d5fd%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638012683848289575%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TovES98x9QSX5NeLv9iid5DyrpcWADfwXrIYalsZsZY%3D&reserved=0> Since I plan to order 3 of the 4 remaining through MolPort, how do you guys feel about also ordering a bunch of reference ligands for other ABHD enzymes. These may also be useful for the EUbOPEN chemogenomics library. What do you think? Let me know if you have any special desires. I will select primarily based on data in Probes & Drugs: ***@***.***<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.probes-drugs.org%2Fcompounds%2Fstandardized%23customset%3D714%40AND&data=05%7C01%7Cmartin.haraldsson%40ki.se%7C9159f85324304f72c98408daad27d5fd%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638012683848289575%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=c7zBEv%2FKLyvoKO3jVS5hQym1heLn1ecYYUgzf2jraW4%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FStructuralGenomicsConsortium%2FCNP6-ABHD2%2Fissues%2F1%23issuecomment-1277710744&data=05%7C01%7Cmartin.haraldsson%40ki.se%7C9159f85324304f72c98408daad27d5fd%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638012683848446239%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ImcS%2FEOkDhmX7UoLOWo4SITxst5Q%2Fhg5ghQXuP5HjZk%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA3M3VXEYM35A5XVL3CTPXULWDAMR3ANCNFSM6AAAAAAQYYMTMA&data=05%7C01%7Cmartin.haraldsson%40ki.se%7C9159f85324304f72c98408daad27d5fd%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638012683848446239%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sa58nio1o8urw6mug8Qc7K%2FaF1TaDoKToWu0rEyaK9A%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by mattodd** [comment]
@Evert-Homan - these are known probes for ABHD's? I confess I did not know there were any.

**Comment by EveCarter** [comment]
Hi all,

I was looking again at the [paper](https://pubs.acs.org/doi/10.1021/acschembio.9b00640) documenting the only known ABHD2 inhibitor (183). From figure 3D, 185 and 186 look fairly specific to ABHD2, as well as 183 and 184 which were discussed in the paper.

![Figure 3D cropped 2](https://user-images.githubusercontent.com/112560282/196212632-33c54aa9-e9ff-4d60-9696-555b3223a9cc.png)

The SI gives SMILES for all of the structures tested in Fig 3D, which I have converted into DataWarrior ([here is the zipped file](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/files/9801758/Structures.in.Figure.3D.2019.paper.zip)). The structures in the SI for 183 and 184 are incorrect. Mario van der Stelt told me that the structures in the SI were the original targets, but that for 183 and 184 side products were accidentally isolated and those are the structures shown in the papers. He thinks there were no other issues, so it is likely the structures of 185 and 186 match those in the SI. I summarised these structures in a [word document](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/files/9801807/Structures.in.Figure.3D.2019.paper.docx).


I thought I would let you all know in case you tried looking at this and were confused! I suggest that we wait and see what results Oliver gets from testing the compounds that have already been synthesised/purchased, but structures 185 and 186 could be helpful in the future.

**Comment by ghost** [comment]
Wow, that was an oversight on my part...nice catch!

**Comment by MFernflower** [comment]
@mattodd @EveCarter are compound ideas based on the original dipiperidinylurea hit still wanted?


![image](https://user-images.githubusercontent.com/3164942/196570244-086bcc32-b30b-46d3-af40-d5f8554e947f.png)

**Comment by ghost** [comment]
@EveCarter The 22 compounds ordered from Enamine have arrived and handed over to Martin Haraldsson, who will register them in the CBCS compound management system.

**Comment by ghost** [comment]
> @OliverArnolds @MartinHaraldsson @mattodd @EveCarter Since I plan to order 3 of the 4 remaining through MolPort, how do you guys feel about also ordering a bunch of reference ligands for other ABHD enzymes. These may also be useful for the EUbOPEN chemogenomics library. What do you think? Let me know if you have any special desires. I will select primarily based on data in Probes & Drugs: https://www.probes-drugs.org/compounds/standardized#customset=714@AND

@EveCarter These 3 remaining analogues as well as 4 'reference' ABHD inhibitors (see attached DW file) arrived last week and have been passed on to @MartinHaraldsson at CBCS for registration and handling. Links with info to the reference inhibitors:

Orlistat: https://www.probes-drugs.org/compounds/standardized#externalid=8853778@AND
JZP 430: https://www.probes-drugs.org/compounds/standardized#externalid=10524994@AND
KT109: https://www.probes-drugs.org/compounds/standardized#externalid=8890416@AND
DO264: https://www.probes-drugs.org/compounds/standardized#externalid=9090197@AND

BW/Evert
[ABHD2_MolPort_delivery_221123.zip](https://github.com/StructuralGenomicsConsortium/CNP6-ABHD2/files/10111111/ABHD2_MolPort_delivery_221123.zip)

**Comment by MartinHaraldsson** [comment]
FYI
The new compounds have been registered and handled By our colmpound collection at CBCS/KI/Scilifelab. 53 compounds are available in DMSO for future testing. 24 homemade and 29 purchased. All are analyzed by HPLC-MS to establish purity and identity. A few compounds from this collection seem to be of low quality.
Martin

Från: Evert-Homan ***@***.***>
Skickat: Tuesday, 29 November 2022 09:26
Till: StructuralGenomicsConsortium/CNP6-ABHD2 ***@***.***>
Kopia: Martin Haraldsson ***@***.***>; Mention ***@***.***>
Ämne: Re: [StructuralGenomicsConsortium/CNP6-ABHD2] First Library Based on Known Literature Inhibitor (Issue #1)


@OliverArnolds<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOliverArnolds&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233624113%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gL9Gi8ljgufnXlcD4kW62BSTAMhH8vnkg8w%2BxDtbR80%3D&reserved=0> @MartinHaraldsson<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMartinHaraldsson&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233779882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=15lw9FczznPYVV%2FBKVNWd9NTRZal9NcnICsM7ZHbPRM%3D&reserved=0> @mattodd<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmattodd&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233779882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Whk3kFOVX1Vl3nR02lAhdLQcRLhOXlFos8W%2B2KAZ8gI%3D&reserved=0> @EveCarter<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEveCarter&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233779882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZTrxCqFDEPgmudz0gFTcMuWIg9NHY0SDlv3f2oEo%2BR4%3D&reserved=0> Since I plan to order 3 of the 4 remaining through MolPort, how do you guys feel about also ordering a bunch of reference ligands for other ABHD enzymes. These may also be useful for the EUbOPEN chemogenomics library. What do you think? Let me know if you have any special desires. I will select primarily based on data in Probes & Drugs: ***@***.***<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.probes-drugs.org%2Fcompounds%2Fstandardized%23customset%3D714%40AND&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233779882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fcIJyZ8VS0dF2y7hc6s6W3SR6kYFx2KBk%2Fe%2B%2BfwGTXA%3D&reserved=0>

@EveCarter<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEveCarter&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233779882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZTrxCqFDEPgmudz0gFTcMuWIg9NHY0SDlv3f2oEo%2BR4%3D&reserved=0> These 3 remaining analogues as well as 4 'reference' ABHD inhibitors (see attached DW file) arrived last week and have been passed on to @MartinHaraldsson<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMartinHaraldsson&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233779882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=15lw9FczznPYVV%2FBKVNWd9NTRZal9NcnICsM7ZHbPRM%3D&reserved=0> at CBCS for registration and handling. Links with info to the reference inhibitors:

Orlistat: ***@***.***<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.probes-drugs.org%2Fcompounds%2Fstandardized%23externalid%3D8853778%40AND&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233779882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=x%2BqQxwfu2gnUfMeqlfxb5ZeCYAgu9d0sZl9%2BEnDP48w%3D&reserved=0>
JZP 430: ***@***.***<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.probes-drugs.org%2Fcompounds%2Fstandardized%23externalid%3D10524994%40AND&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233779882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gAQcrkR7pt3dHGup2ySNS88DabrI2xw0X%2FkXEUAnKEM%3D&reserved=0>
KT109: ***@***.***<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.probes-drugs.org%2Fcompounds%2Fstandardized%23externalid%3D8890416%40AND&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233779882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jywt1rlYm%2FNO7QDIyZCyqNejwZTF%2BmlGrpoJjRlq3Xg%3D&reserved=0>
DO264: ***@***.***<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.probes-drugs.org%2Fcompounds%2Fstandardized%23externalid%3D9090197%40AND&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233779882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FjP%2BkCoNT27H8D15j4f2gTh5DW9LeahnBLebBgaDXmY%3D&reserved=0>

BW/Evert
ABHD2_MolPort_delivery_221123.zip<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FStructuralGenomicsConsortium%2FCNP6-ABHD2%2Ffiles%2F10111111%2FABHD2_MolPort_delivery_221123.zip&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233779882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=f4tkFy2HpymBKwhV2EhMd1UBBmmvqKlUcONzDFOT0%2BA%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FStructuralGenomicsConsortium%2FCNP6-ABHD2%2Fissues%2F1%23issuecomment-1330259061&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233779882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5yecR1pDOGPpjdlHe%2FvkrEUdOaKIJajg9YK%2F%2B2pFStk%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA3M3VXFL5JGH2GVTCHIQFJ3WKW43HANCNFSM6AAAAAAQYYMTMA&data=05%7C01%7Cmartin.haraldsson%40ki.se%7Ce0c487efeb3f4deba50708dad1e369bc%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638053072233779882%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zieLIcUNeVB2TPekE5gl%2BiWYLmm0qtD3PDor4JoK5yM%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by EveCarter** [comment]
Closing this issue as work has finished on this library. This issue has been linked in the wiki.
